title: INSA Rasprack
description: A website dedicated to the INSA Rasprack project.
theme: just-the-docs

url: "https://qperez.github.io"
baseurl: "/insa-rasprack"   # correspond au nom de ton repo

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template

# Dossier contenant tes pages de documentation
collections:
  docs:
    output: true
    permalink: /:collection/:path/

# Configuration de la navigation
#just_the_docs:
#  collections:
#    docs:
#      name: Documentation
#      nav_exclude: false